### ISSUE TITLE
Python solution for 3rd problem

### ISSUE THREAD

**Issue by Samiksha99** [L-ByDo/CODE-FIESTA-1.0#4]

**Comment by Apoorve73** [comment]
Thank you @Samiksha99 for creating this issue. I have reviewed your pull request but abiding to the repo structure the filename should be TDS.py! Kindly make these changes and submit the PR again!

**Comment by Samiksha99** [comment]
sure!

**Comment by Apoorve73** [comment]
Great work! :+1:  PR#3 merged
